### ISSUE TITLE
Project Tracking System

### ISSUE THREAD

**Issue by Obuli001** [AldoStalin/SonaITHackathon#11]
Project Name: Project Tracking System.
Short Project Description: Tracking the project work daily.
Team Name: Tracker
Team Members: S.M.Obuli karthikeyan , P.navaneethan.
Demo Link: https://youtu.be/A4TivdTUYVA
Repository Link: https://github.com/Obuli001/project-tracking-system
Labels: window Application.

 🔥 Your Pitch
The aim of the project is to track the daily work in the company of the each employee. The employee has to update the daily work that doing in their company.For this we create the windows application to see their the employee activites.

✅ Checklist

Before you post the issue**:
- [x] You have followed the issue title format.
- [x] You have applied the correct labels.
- [x] You have mentioned the correct labels.
- [x] You have provided all the information correctly.
